#!/bin/bash
# Integration test for Python groups client

where=`which canfar-is-member`
if [[ "$?" != "0" ]]; then
    echo "ERROR: Couldn't locate canfar-is-member"
    exit 1
else
    echo "*** Testing $where ***"
fi

if [ -z $CADCTESTCERTS ]; then
    echo "CADCTESTCERTS not defined"
    exit 1
fi

testcert='x509_CADCAuthtest1.pem'

if [ ! -e "$CADCTESTCERTS/$testcert" ]; then
    echo "Couldn't find $CADCTESTCERTS/$testcert"
    exit 1
fi

# Some groups have to be set up manually in advance in order for this
# to work. If the python client is extended in the future so that
# groups and membership can be written, these can be generated
# on-the-fly.
MEMBERCMD="canfar-is-member --certfile=$CADCTESTCERTS/$testcert"
TESTGRP1=PythonIntTest-Group1
TESTGRP2=PythonIntTest-Group2

echo -n "check user is a member of group 1..."
output=`$MEMBERCMD $TESTGRP1 2> /dev/null`
[[ "$?" != "0" ]] && echo " cmd [FAIL]" && exit -1
if [[ "$output" != "True" ]]; then echo " output [FAIL]"; exit -1; fi
echo " [OK]"

echo -n "check user is a member of group 1 or group 2..."
output=`$MEMBERCMD $TESTGRP1 $TESTGRP2 2> /dev/null`
[[ "$?" != "0" ]] && echo " cmd [FAIL]" && exit -1
if [[ "$output" != "True" ]]; then echo " output [FAIL]"; exit -1; fi
echo " [OK]"

echo -n "check user is not member of group 2..."
output=`$MEMBERCMD $TESTGRP2 2> /dev/null`
[[ "$?" != "0" ]] && echo " cmd [FAIL]" && exit -1
if [[ "$output" != "False" ]]; then echo " output [FAIL]"; exit -1; fi
echo " [OK]"

echo -n "check user is not member of non-existent group..."
output=`$MEMBERCMD thisIsNotAGroup 2> /dev/null`
[[ "$?" != "0" ]] && echo " cmd [FAIL]" && exit -1
if [[ "$output" != "False" ]]; then echo " output [FAIL]"; exit -1; fi
echo " [OK]"
