#!/usr/bin/python
#!python
"""Get or put a file to the data web service"""

from cadc.data.client import DataClient
from cadc.common.parser import BaseParser
import sys
import logging

description = "Get or Put a file to the data web service."

if __name__=='__main__':

    # Parse the command line
    parser = BaseParser(description=description)
    parser.add_argument('dir', choices=['get','put'], help='direction')
    parser.add_argument('--uri', required=True,
                        help="URI of file (e.g., 'ad:ARCHIVE/filename')")
    parser.add_argument('--file', default=None,
                        help='Local file name')

    args=parser.parse_args()

    certfile=args.certfile
    dir=args.dir
    if dir == 'put':
        is_put = True
    else:
        is_put = False
    uri = args.uri
    file = args.file
    if file is None:
        if dir == 'put':
            raise ValueError("--file must be specified for a put")
        else:
            # Default file name from URI (text after final '/')
            file = (uri.split('/'))[-1]

    # Create a data client and logger
    try:
        # Schema validation is slow due to large initial overhead (~1.5s) ?
        c = DataClient(certfile=certfile, schema_validate=False)
        logger = c.get_logger(verbose=args.verbose, debug=args.debug,
                              quiet=args.quiet)
    except Exception as e:
        print e
        sys.exit(1)


    # Copy file
    try:
        c.transfer_file(uri,file,is_put)

    except Exception as e:
        logger.exception("Failed to copy file:\n%s" % str(e) )
        sys.exit(1)

    sys.exit(0)
